DVB-S sat config: set default nothing connected
-this solves the problem empty list of satellites
File "/usr/lib/enigma2/python/Screens/ScanSetup.py", line 604, in
__init__
File
"/usr/lib/enigma2/python/Plugins/SystemPlugins/Satfinder/plugin.py",
line 101, in createSetup
if len(nimmanager.getTransponders(int(self.tuning_sat.value))) < 1: #
Only offer 'predefined transponder' if some transponders exist
ValueError: invalid literal for int() with base 10: ''

(cherry picked from commit aa279418f87e58c5841a3ed553b509526e11021c)
Signed-off-by: Erik Slagter <erik@openpli.org>