NimSelection: use slot_name from NIM class to get slot name
IndexError: list index out of range will occur if there are more that 4 tuners.

Instead use slot_name from NIM class that already provides the same information.
and works without issues for 26 slot positions (A to Z).

(cherry picked from commit 4303fcd4144d0aad588c585e6ab54f824e2a50a6)
Signed-off-by: Erik Slagter <erik@openpli.org>